variables:
   GIT_SUBMODULE_STRATEGY: recursive

image:
   name: registry.gitlab.com/matclab/rofi-file-selector/rfs-test:0.2

test:
   script:
      - bats --formatter junit tests
   artifacts:
      reports:
         junit: TestReport*.xml
